### ISSUE TITLE
Fail to handle connection where schema needs to be specified

### ISSUE THREAD

**Issue by leungi** [moodymudskipper/easydb#2]
Reprex below.

``` r
library(easydb)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

## Try 1
drv <- DBI::dbDriver("Oracle")
con <- db_connect(
  drv,
  dbname = "my_db",
  username = "read",
  password = "read",
  schema = "my_schema"
)

con$my_tbl
#> Error in .oci.SendQuery(conn, statement, data = data, prefetch = prefetch,  : 
#>  ORA-00942: table or view does not exist

## Try 2
specs <- list(
  drv = DBI::dbDriver("Oracle"),
  dbname = "my_db",
  username = "read",
  password = "read"
)

con <- db_connect(specs)

my_tbl <- dbplyr::in_schema("my_schema", "my_tbl")

con$my_tbl
#> Error in .oci.SendQuery(conn, statement, data = data, prefetch = prefetch,  : 
#>  ORA-00942: table or view does not exist

# works
dplyr::tbl(con, my_tbl)
```

<sup>Created on 2019-09-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by moodymudskipper** [comment]
I cannot reproduce it and I don't have Oracle available to test but are you sure that you have a table named `"my_tbl"` in your DB (as opposed to a variable `my_tbl` containing a variable name?

`con$my_tbl` is equivalent to  `dplyr::tbl(con, "my_tbl")` (litterally), not `dplyr::tbl(con, my_tbl)` as your last line seems to assume.

Would it be the source of the issue ?

**Comment by leungi** [comment]
Apologies; I could've picked a better variable name to avoid ambiguity, but I'm sure "my_tbl" exists in "my_schema".

How should one specify a schema and table name via your class method?

Is this valid: 
con$'my_schema.mytbl'

**Comment by moodymudskipper** [comment]
Could you try this ?

```
`$.DBIConnection` <- function(con, x){
  x <- strsplit(x, ".", fixed = TRUE)[[1]]
  if(length(x)==1) dplyr::tbl(con,x) else dplyr::tbl(con, dbplyr::in_schema(x[1], x[2]))
}

`$<-.DBIConnection` <- function(con, x, value) {
  x <- strsplit(x, ".", fixed = TRUE)[[1]]
  if(length(x)==1) 
    dplyr::copy_to(con, value, x, overwrite = TRUE, temporary = FALSE) 
  else 
    dplyr::copy_to(con, value, dbplyr::in_schema(x[1], x[2]), overwrite = TRUE, temporary = FALSE)
  con}
```

The problem is that dots in table names are sometimes legal, but that could be a restriction of the package to not support that case I guess.

**Comment by moodymudskipper** [comment]
Sorry I've not been very clear, the above should make `con$my_schema.mytbl` work.

`con$my_schema.mytbl2 <- cars` should work too but for some reason I can't overwrite it once copied, i think it's a dbplyr bug

**Comment by leungi** [comment]
Thanks for the prompt reply.

`con$schema.table` works 👍

**Comment by moodymudskipper** [comment]
Great, I'm glad it worked out. I'm reopening because I think it might make sense to implement this.

**Comment by moodymudskipper** [comment]
done, with more consistency and other improvements, see new README
